ruby-on-rails-7x-para-iniciantes/modulo-05-avancando-no-rails/rubyonrailsclub-blog/config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get "welcome/index"
  namespace :administrate do
    resources :articles
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "welcome#index"
end

ruby-on-rails-7x-para-iniciantes/modulo-05-avancando-no-rails/rubyonrailsclub-blog/app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

ruby-on-rails-7x-para-iniciantes/modulo-05-avancando-no-rails/rubyonrailsclub-blog/app/models/article.rb
# frozen_string_literal: true

class Article < ApplicationRecord
  extend FriendlyId
  friendly_id :title, use: :slugged
end

ruby-on-rails-7x-para-iniciantes/modulo-05-avancando-no-rails/rubyonrailsclub-blog/app/controllers/administrate/articles_controller.rb
# frozen_string_literal: true

module Administrate
  class ArticlesController < ApplicationController
    before_action :set_article, only: [:show, :edit, :update, :destroy]

    # GET /articles or /articles.json
    def index
      @articles = Article.all
    end

    # GET /articles/1 or /articles/1.json
    def show
    end

    # GET /articles/new
    def new
      @article = Article.new
    end

    # GET /articles/1/edit
    def edit
    end

    # POST /articles or /articles.json
    def create
      @article = Article.new(article_params)

      respond_to do |format|
        if @article.save
          format.html { redirect_to(article_url(@article), notice: "Article was successfully created.") }
          format.json { render(:show, status: :created, location: @article) }
        else
          format.html { render(:new, status: :unprocessable_entity) }
          format.json { render(json: @article.errors, status: :unprocessable_entity) }
        end
      end
    end

    # PATCH/PUT /articles/1 or /articles/1.json
    def update
      respond_to do |format|
        if @article.update(article_params)
          format.html { redirect_to(article_url(@article), notice: "Article was successfully updated.") }
          format.json { render(:show, status: :ok, location: @article) }
        else
          format.html { render(:edit, status: :unprocessable_entity) }
          format.json { render(json: @article.errors, status: :unprocessable_entity) }
        end
      end
    end

    # DELETE /articles/1 or /articles/1.json
    def destroy
      @article.destroy!

      respond_to do |format|
        format.html { redirect_to(articles_url, notice: "Article was successfully destroyed.") }
        format.json { head(:no_content) }
      end
    end

    private

    # Use callbacks to share common setup or constraints between actions.
    def set_article
      # @article = Article.find(params[:id])
      @article = Article.friendly.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def article_params
      params.require(:article).permit(:title, :body)
    end
  end
end

ruby-on-rails-7x-para-iniciantes/modulo-05-avancando-no-rails/rubyonrailsclub-blog/app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

ruby-on-rails-7x-para-iniciantes/modulo-05-avancando-no-rails/rubyonrailsclub-blog/app/controllers/welcome_controller.rb
# frozen_string_literal: true

class WelcomeController < ApplicationController
  def index
    @articles = Article.all
  end
end

ruby-on-rails-7x-para-iniciantes/modulo-05-avancando-no-rails/rubyonrailsclub-blog/app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

ruby-on-rails-7x-para-iniciantes/modulo-05-avancando-no-rails/rubyonrailsclub-blog/app/helpers/articles_helper.rb
# frozen_string_literal: true

module ArticlesHelper
end

ruby-on-rails-7x-para-iniciantes/modulo-05-avancando-no-rails/rubyonrailsclub-blog/app/helpers/welcome_helper.rb
# frozen_string_literal: true

module WelcomeHelper
end

ruby-on-rails-7x-para-iniciantes/modulo-05-avancando-no-rails/rubyonrailsclub-blog/app/views/administrate/articles/_article.html.erb
<div id="<%= dom_id article %>">
  <p>
    <strong>Title:</strong>
    <%= article.title %>
  </p>

  <p>
    <strong>Body:</strong>
    <%= article.body %>
  </p>

</div>

ruby-on-rails-7x-para-iniciantes/modulo-05-avancando-no-rails/rubyonrailsclub-blog/app/views/administrate/articles/_form.html.erb
<%= form_with(model: [:administrate, article]) do |form| %>
  <% if article.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
        <% article.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :body, style: "display: block" %>
    <%= form.text_area :body %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

ruby-on-rails-7x-para-iniciantes/modulo-05-avancando-no-rails/rubyonrailsclub-blog/app/views/administrate/articles/edit.html.erb
<h1>Editing article</h1>

<%= render "form", article: @article %>

<br>

<div>
  <%= link_to "Show this article", [:administrate, @article] %> |
  <%= link_to "Back to articles", administrate_articles_path %>
</div>

ruby-on-rails-7x-para-iniciantes/modulo-05-avancando-no-rails/rubyonrailsclub-blog/app/views/administrate/articles/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Articles</h1>

<div id="articles">
  <% @articles.each do |article| %>
    <%= render article %>
    <p>
      <%= link_to "Show this article", [:administrate, article] %>
    </p>
  <% end %>
</div>

<%= link_to "New article", new_administrate_article_path %>

ruby-on-rails-7x-para-iniciantes/modulo-05-avancando-no-rails/rubyonrailsclub-blog/app/views/administrate/articles/new.html.erb
<h1>New article</h1>

<%= render "form", article: @article %>

<br>

<div>
  <%= link_to "Back to articles", administrate_articles_path %>
</div>

ruby-on-rails-7x-para-iniciantes/modulo-05-avancando-no-rails/rubyonrailsclub-blog/app/views/administrate/articles/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @article %>

<div>
  <%= link_to "Edit this article", edit_administrate_article_path(@article) %> |
  <%= link_to "Back to articles", administrate_articles_path %>

  <%= button_to "Destroy this article", [:administrate, @article], method: :delete %>
</div>

ruby-on-rails-7x-para-iniciantes/modulo-05-avancando-no-rails/rubyonrailsclub-blog/app/views/articles/_form.html.erb
<%= form_with(model: article) do |form| %>
  <% if article.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
        <% article.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :body, style: "display: block" %>
    <%= form.text_area :body %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

ruby-on-rails-7x-para-iniciantes/modulo-05-avancando-no-rails/rubyonrailsclub-blog/app/views/articles/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Articles</h1>

<div id="articles">
  <% @articles.each do |article| %>
    <%= render article %>
    <p>
      <%= link_to "Show this article", article %>
    </p>
  <% end %>
</div>

<%= link_to "New article", new_article_path %>

ruby-on-rails-7x-para-iniciantes/modulo-05-avancando-no-rails/rubyonrailsclub-blog/app/views/articles/new.html.erb
<h1>New article</h1>

<%= render "form", article: @article %>

<br>

<div>
  <%= link_to "Back to articles", articles_path %>
</div>

ruby-on-rails-7x-para-iniciantes/modulo-05-avancando-no-rails/rubyonrailsclub-blog/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RubyonrailsclubBlog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

ruby-on-rails-7x-para-iniciantes/modulo-05-avancando-no-rails/rubyonrailsclub-blog/app/views/welcome/_article.html.erb
<div>
  <p>
    <strong>Title:</strong>
    <%= article.title %>
  </p>
</div>

ruby-on-rails-7x-para-iniciantes/modulo-05-avancando-no-rails/rubyonrailsclub-blog/app/views/welcome/index.html.erb
<h1>Articles</h1>
<div id="articles">
  <% @articles.each do |article| %>
    <%= render partial: "article", locals: { article: article } %>
  <% end %>
</div>